# IMPUTATION DEFAULT VALUES ==========================================================================

# ALGORITHM DEFAULT VALUES : MATRIX COMPLETION
[cdrec]
rank = 2
epsilon = 0.000001
epsilon_str = "E-6"
iteration = 100

[iterative_svd]
rank = 2

[grouse]
max_rank = 2

[rosl]
rank = 2
regularization = 2

[soft_impute]
max_rank = 5

[spirit]
k = 5
w = 6
lvalue = 1

[svt]
tau = 1


# ALGORITHM DEFAULT VALUES : PATTERN SEARCH
[stmvl]
window_size = 2
gamma = 0.85
alpha = 7

[dynammo]
h = 5
max_iteration = 5
approximation = true

[tkcm]
rank = 2

# ALGORITHM DEFAULT VALUES : STATISTICS
[iim]
learning_neighbors = 10
algorithm_code = "iim 2"

# ALGORITHM DEFAULT VALUES : DEEP LEARNING
[mrnn]
hidden_dim = 10
learning_rate = 0.01
iterations = 50
sequence_length = 7

[brits]
model = "brits_i_univ"
epoch = 10
batch_size = 10
nbr_features = 1
hidden_layers = 64

[deep_mvi]
max_epoch = 100
patience = 2

[mpin]
incre_mode = "data+state+transfer"
window = 1
k = 10
learning_rate = 0.01
weight_decay = 0.1
epochs = 10
threshold = 0.25
base = "SAGE"

[pristi]
target_strategy = "hybrid"
unconditional = false
seed = 42
device = "cpu"

# OPTIMIZER DEFAULT VALUES ==========================================================================
[greedy]
n_calls = 250
metrics='RMSE'

[bayesian]
n_calls = 2
n_random_starts = 50
acq_func = 'gp_hedge'
metrics='RMSE'

[pso]
n_particles = 50
c1 = 0.5
c2 = 0.3
w = 0.9
iterations=10
n_processes=1
metrics='RMSE'

[sh]
num_configs = 10
num_iterations = 2
reduction_factor = 10
metrics="RMSE"

[ray_tune]
metrics = 'RMSE'
n_calls = 1
max_concurrent_trials = -1

# DOWNSTREAM DEFAULT VALUES ==========================================================================
[forecaster-naive]
strategy = "mean"
window_length = 10
sp = 5

[forecaster-exp-smoothing]
trend = "additive"
seasonal = "additive"
sp = 5

[forecaster-prophet]
seasonality_mode = "additive"
n_changepoints = 25




# FUNCTION DEFAULT VALUES ==========================================================================

# FUNCTION DEFAULT VALUES : EXPLAINER
[explainer]
splitter = 10
nbr_series = 15

# FUNCTION DEFAULT VALUES : LOADER
[loading]
load_dataset = "drift"
load_algorithm = "cdrec"
load_normalization = "Normal"
load_series = ["-3:all_except_two"]
load_missing_rate = "20"
load_scenario = "missing_pourcentage"
load_series_contamination = []
load_missing_rate_contamination = "0"


[colors]
chart = ["#696969", "#2b908f", "#a6c96a", "#876d5d", "#8f10ba", "#f7a35c", "#434348", "#f15c80", "#910000", "#8085e9", "#365e0c", "#90ed7d"]
plot = ['dimgrey', 'plum', 'lightblue', 'mediumseagreen', 'khaki', 'gold', 'darkslategrey', 'hotpink', 'chocolate', 'lightseagreen', 'wheat']


# MODEL DEFAULT VALUES ==========================================================================

# MODEL PRISTI ==========================================================================
[train]
epochs = 20
batch_size = 16
lr = 0.01
valid_epoch_interval = 5
is_lr_decay = true

[diffusion]
layers = 2
channels = 1
nheads = 1
diffusion_embedding_dim = 64
beta_start = 0.0001
beta_end = 0.2
num_steps = 100
schedule = "quad"
is_adp = true
proj_t = 8
is_cross_t = true
is_cross_s = true

[model]
is_unconditional = 0
timeemb = 64
featureemb = 8
target_strategy = "hybrid"
use_guide = true
mask_sensor = []
