name: Pytest - ImputeGAP - LIB

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmlpack-dev libopenblas-dev python3-dev build-essential uv
        pip install --upgrade google protobuf
        uv pip install imputegap==1.0.8


    - name: Run pytest
      run: |
        python -m pytest ./tests/test_lib.py