name: VERSIONING 3.11.5 - Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmlpack-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install python3-dev build-essential
        pip install --upgrade google protobuf
        pip install -r requirements.txt
        pip install mypy
        pip install pytest


    - name: Run pytest
      run: |
        python -m pytest ./tests/test_pipeline.py